# @format

version: '3'

services:
  frontend:
    image: money-transfer/frontend
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: money-transfer/backend
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5000:5000'
