# @format

version: '3'

services:
  frontend:
    image: internal_money-frontend-image
    container_name: internal_money-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: internal_money-backend-image
    container_name: internal_money-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5000:5000'
